name: test
config:
  provider: ec2
  region: 'us-west-2'
  ami: 'ami-ff527ecf'
  keyname: sarath
  key: '/etc/ansible/sarath.pem'
  user: 'ec2-user'
  operation:
    type: script
    file: 'script1.sh'

